version: '3.8'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins
    ports:
      - "9090:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Docker socket bind mount
      - jenkins_home:/var/jenkins_home
    privileged: true  # Root-level access
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    user: root    # 🟢 Ensure Jenkins runs as root user
    restart: always

volumes:
  jenkins_home:
